name: WellOnline
version: 1.0.4
main: me.enot.WellOnline

commands:
  check:
    description: "Команда для просмотра истории онлайна отдельных игроков | Command for checking history of online some players"
  wellonline:
    description: "Основная команда плагина | Main plugin command"